--[[ hms_schema_v2.lua

Conversion of hms_schema.lua utilising schema.lua

]]

local s = require("schema")

local hms_schema = s.Record {
	CIEF = s.Boolean, 
	PEF = s.Boolean, 
	RFEF = s.Boolean, 
	TIauthno = s.Optional(s.String),
	TIescrow = s.Boolean, 
	UAAtrustedCert = s.String, 
	anon_priv = s.Record {
		eSealPublicKey = s.Boolean, 
		ectEnabled = s.Boolean, 
		ectMaxECT = s.Boolean, 
		egmBetMeter = s.Boolean, 
		egmCreditDenomination = s.Boolean, 
		egmCreditInputEnabled = s.Boolean, 
		egmCreditMeter = s.Boolean, 
		egmDoorState = s.Boolean, 
		egmDoorsClosed = s.Boolean, 
  		egmInAuditMode = s.Boolean,
 		egmInFault = s.Boolean, 
  		egmInQuietFault = s.Boolean, 
  		egmInTestMode = s.Boolean, 
  		egmKeySwitchStatus = s.Boolean,
  		egmMaxRTP = s.Boolean,
  		egmMinRTP = s.Boolean, 
  		egmOK = s.Boolean,
  		egmState = s.Boolean,
  		egmWinMeter = s.Boolean,
  		idCommissionUID = s.Boolean, 
  		idDeviceType = s.Boolean,
  		idInterfaceVersion = s.Boolean,
  		idLogicUID = s.Boolean,
  		idMachineID = s.Boolean,
  		idMfrAlpha3 = s.Boolean, 
  		idMfrName = s.Boolean, 
  		locCountryCode = s.Boolean, 
  		locCurrencyCode = s.Boolean,
  		locFloorLocation = s.Boolean, 
  		locStateProv = s.Boolean, 
  		locVenueAddress = s.Boolean, 
  		locVenueID = s.Boolean, 
  		locVenueName = s.Boolean, 
  		locVenueType = s.Boolean, 
  		machineInDebugMode = s.Boolean, 
  		machineReady = s.Boolean, 
  		machineShuttingDown = s.Boolean,
  		networkEthAddr = s.Boolean,
  		networkIP = s.Boolean,
  		playEnabled = s.Boolean,
  		secLogicSealOk = s.Boolean,
  		secMachineCert = s.Boolean,
  		secQMAcert = s.Boolean,
  		secSUAcerts = s.Boolean,
  		timeTimezone = s.Boolean,
  		userCPUstats = s.Boolean,
  		userInstructionStats = s.Boolean,
  		userMemoryStats = s.Boolean,
  		userUserList = s.Boolean,
  		wwwCert = s.Boolean,
	},
	anonpass = s.String,
	auditmode = s.Boolean,
	betMeter = s.AllOf(s.NonNegativeNumber, s.Integer),
	cAuditCommonResults = s.Collection(s.OneOf(s.Record { uid = s.String }, s.String)), -- Rob: Confirm if this is what you want
	ccLastTID = s.String,
	commissionuid = s.String,
	countrycode = s.String,
	creditInputLast = s.Boolean,
	currencycode = s.String,
	devMeters = s.Record {
		bna = s.Record {
			notesin = s.Boolean, 
			notesincount = s.Boolean, 
			notesrej = s.Boolean, 
			ticketin = s.Boolean, 
			ticketincount = s.Boolean,
		}, 
		ca = s.Record {
			cashbox = s.Boolean, 
			coinsin = s.Boolean, 
		}, 
		hopper = s.Record { 
			coinsout = s.Boolean, 
			refill = s.Boolean,
		}, 
		tp = s.Record {
			ticketout = s.Boolean, 
			ticketoutcount = s.Boolean,
		}, 
	}, 
	devStatus = s.Record {
		bna = s.Optional(s.Record {
			connected = s.Boolean, 
			denomStatus = s.Collection(
				s.Optional(s.Boolean)
			),
			fds = s.String, -- todo: restrict to ASCII chars? 
			full = s.Boolean, 
			metersByDenom = s.Collection(
				s.Integer, -- 10 
				s.Integer, -- 100
				s.Integer,  -- 20 
				s.Integer, -- 5
				s.Integer -- 50
			),
			stacker = s.Boolean, 
			status = s.String, 
			upgradeable = s.Boolean,
		}),
		ca = s.Optional(s.Record {
			connected = s.Boolean, 
			denom = s.Integer, 
			divertercb = s.Boolean, 
			fds = s.String, -- todo: restrict to ASCII chars? 
			status = s.String, 
			upgradeable = s.Boolean,
		}),
		hopper = s.Optional(s.Record { 
			connected = s.Boolean, 
			denom = s.Integer, 
			full = s.Boolean, 
			status = s.String
		}), 
		tp = s.Optional(s.Record {
			connected = s.Boolean, 
			fds = s.String, -- todo: restrict to ASCII chars? 
			status = s.String, 
			upgradeable = s.Boolean,
		})
	},
	devSupported = s.Record { 
		bna = s.Boolean, 
		ca = s.Boolean, 
		hopper = s.Boolean, 
		tp = s.Boolean, 
	}, 
	doorstate = s.Record { 
		aux = s.Boolean, 
		belly = s.Boolean, 
		bna = s.Boolean, 
		dropbox = s.Boolean, 
		logic = s.Boolean, 
		main = s.Boolean, 
	}, 
	ectenabled = s.Boolean, 
	ectsubsn = s.AllOf(s.NonNegativeNumber, s.Integer), 
	egmcrdenom = s.AllOf(s.NonNegativeNumber, s.Integer), 
	egmokex = s.Boolean, 
	egmokexrt = s.Any, -- Clarify with Rob what this table is 
	eventb = s.Record { 
		SLx = s.Record { 
			cash = s.Integer, 
			coinv = s.Integer, 
			display = s.Integer, 
			game = s.Integer, 
			hopper = s.Integer, 
			license = s.Integer, 
			lp = s.Integer, 
			machine = s.Integer, 
			notev = s.Integer, 
			security = s.Integer, 
			ticket = s.Integer, 
			user = s.Integer, 
		}, 
		bot = s.Integer, 
		buff = s.Collection(s.Record {
			cat = s.Optional(s.String), 
			csn = s.Optional(s.Integer), 
			data = s.Optional(s.Record {
				commuid = s.Optional(s.String), 
				logicuid = s.Optional(s.String),
				gameid = s.Optional(s.String),
				var = s.Optional(s.Integer),
				username = s.Optional(s.String),
				pdtime = s.Optional(s.Integer), 
				reason = s.Optional(s.String), 
				transid = s.Optional(s.String), 
				amt = s.Optional(s.Integer),
				tser = s.Optional(s.Integer), 
				authno = s.Optional(s.String),
			}),
			eventid = s.Optional(s.String), 
			next = s.Optional(s.Integer), 
			prev = s.Optional(s.Integer), 
			sn = s.Optional(s.Integer), 
			tt = s.Optional(s.Integer), 
			ttl = s.Optional(s.Integer),
		}),		
		catlsn = s.Record {
			cash = s.Integer, 
			coinv = s.Integer, 
			display = s.Integer, 
			game = s.Integer, 
			hopper = s.Integer, 
			license = s.Integer, 
			lp = s.Integer, 
			machine = s.Integer, 
			notev = s.Integer, 
			security = s.Integer,
			ticket = s.Integer, 
			user = s.Integer, 
		}, 
		fullcnt = s.Integer, 
		levent = s.Any,  -- Ask Rob for details
		lsn = s.Integer, 
		num = s.Integer, 
		size = s.Integer, 
		slxsum = s.Integer, 
		top = s.Integer, 
	},
	fault = s.Boolean, 
	faultlist = s.Any, -- Ask Rob for details 
	faultquietlist = s.Any, -- Ask Rob for details 
	gambleattempt = s.Integer, 
	gamblelastattemptno = s.Integer, 
	gambleprop = s.Record {
		maxattempts = s.Integer, 
		prizelimit = s.Integer,
	},
	gameSetVar = s.Boolean, 
	games = s.Collection(s.Record {
		gef = s.Boolean, 
		languages = s.Record {
			eng = s.Boolean
		},
		meters = s.Record { 
			gameswon = s.Integer, 
			lpwin = s.Integer,
			stroke = s.Integer, 
			turnover = s.Integer, 
			wins = s.Integer, 
		},
		progr = s.Optional(s.Collection(s.Record { 
			adjneg = s.Integer, 
			adjpos = s.Integer, 
			atv = s.Number, 
			ceiling = s.Integer, 
			games = s.String, 
			hits = s.Integer, 
			hrate = s.Number, 
			liab = s.Number, 
			mode = s.String, 
			modes = s.Record { 
				lp = s.Boolean, 
				sap = s.Boolean, 
			},
			name = s.String,
			pinc = s.Number, 
			pluid = s.String, 
			prizepo = s.Number, 
			ptm = s.String, 
			rtp = s.Number, 
			sup = s.Integer, 
			theme = s.String, 
			turnover = s.Integer, 
			vis = s.Boolean, 
			wins = s.Integer, 
		})),
		prop = s.Record { 
			gameid = s.String, 
			gamename = s.String, 
			gamever = s.String,  
			gameyear = s.Integer, 
			maxbet = s.Integer,
			minbet = s.Integer, 
			paylines = s.Integer, 
			pnum = s.Integer,
		},
		var = s.Integer, 
		varlist = s.Collection(s.Record {
			notes = s.Optional(s.String), 
			rtp = s.Number, 
			stddev = s.Number, 
			tpw = s.Integer,
		}),
		varmeters = s.Optional(s.Collection(s.Record {
			notes = s.Optional(s.String), 
			rtp = s.Optional(s.Number), 
			stddev = s.Optional(s.Number), 
			tpw = s.Optional(s.Integer),
			gameswon = s.Optional(s.Integer), 
			lpwin = s.Optional(s.Number), 
			stroke = s.Optional(s.Integer), 
			turnover = s.Optional(s.Integer), 
			wins = s.Optional(s.Integer),
		})),
	}), 
	gamesEnabled = s.Integer, 
	lastgame = s.String, 
	lastseid = s.String,
	logicsealok = s.Boolean,
	logicuid = s.String, 
	machineid = s.String, 
	machinelanguage = s.String, 
	machinelanguages = s.Record {
		eng = s.Boolean, 
	},
	machineready = s.Boolean, 
	maxbet = s.Integer, 
	meterdenom = s.Number, 
	meters = s.Record { 
		cancelcredit = s.Integer, 
		cashbox = s.Integer, 
		coinsin = s.Integer, 
		coinsout = s.Integer, 
		ectin = s.Integer, 
		ectout = s.Integer, 
		gambleturnover = s.Integer, 
		gamblewin = s.Integer, 
		gameswon = s.Integer, 
		notesin = s.Integer, 
		notesincount = s.Integer, 
		notesrej = s.Integer, 
		refill = s.Integer, 
		stroke = s.Integer, 
		ticketin = s.Integer, 
		ticketincount = s.Integer, 
		ticketout = s.Integer, 
		ticketoutcount = s.Integer, 
		turnover = s.Integer, 
		wins = s.Integer,
	}, 
	midstrl = s.String, 
	midstrs = s.String, 
	mot = s.Integer, 
	nume = s.Integer, 
	numg = s.Integer, 
	osversion = s.String, 
	qusercnt = s.Integer, 
	ramclearfull = s.Boolean, 
	rtpmax = s.Number, 
	rtpmin = s.Number, 
	slnum = s.Integer, 
	sscert = s.String, 
	state = s.String, 
	stateprov = s.String, 
	substate = s.String, 
	systemlockups = s.Any, -- Check with Rob
	testmode = s.Boolean, 
	timeOSD = s.Boolean, 
	timeset = s.Boolean, 
	timezone  = s.Integer, 
	timezoneset = s.Boolean, 
	winMeter = s.Number, 
	woocount = s.Number,
}

hms = {} 
hms.hms_schema = hms_schema

return hms